version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    container_name: dnsrr-nginx
    networks:
      - dnsrr-network

  front:
    build: ./frontend
    ports:
      - '8080'
    container_name: dnsrr-front
    environment:
      - NODE_ENV=production
      - DEBUG=frontend:*
    networks:
      - dnsrr-network

  back:
    build: ./backend
    ports:
      - '3000'
    container_name: dnsrr-back
    environment:
      - NODE_ENV=production
      - DEBUG=backend:*
    networks:
      - dnsrr-network

  redis:
    image: redis
    ports:
      - '6379'
    container_name: dnsrr-redis
    volumes:
      - ./redis:/data
    networks:
      - dnsrr-network
    command: redis-server --appendonly yes

networks:
  dnsrr-network:
    driver: bridge
